Apps/proveedor/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required

from Apps.proveedor.views import *

app_name = 'proveedor'
urlpatterns = [
    # proveedores
    url(r'^proveedor_list/$', login_required(ProveedoresListView.as_view()), name='proveedor_list'),
    url(r'^proveedor_detail/(?P<pk>\d+)$', ProveedoresDetailView.as_view(), name='proveedor_detail'),
    url(r'^proveedor_add/$', proveedor_create, name='proveedor_add'),
    url(r'^proveedor_update/(?P<pk>\d+)$', Update.as_view(), name='proveedor_update'),
    url(r'^proveedor_delete/(?P<pk>\d+)$', Delete.as_view(), name='proveedor_delete'),

    # productos
    url(r'^producto_list/$', login_required(ProductosListView.as_view()), name='producto_list'),
    url(r'^producto_detail/(?P<pk>\d+)$', ProductosDetailView.as_view(), name='producto_detail'),
    url(r'^producto_add/$', productoCreate, name='producto_add'),
    url(r'^producto_update/(?P<pk>\d+)$', ProductoUpdate.as_view(), name='producto_update'),
    url(r'^producto_delete/(?P<pk>\d+)$', ProductoDelete.as_view(), name='producto_delete'),

    # Categorias Productos
    url(r'^categoria_create/$', categoriaCreate, name='categoria_create'),

    # Actualizar Stock
    url(r'^actualizar_stock/(?P<pk>\d+)$', actualizarStock, name='actualizar_stock')

]

remanso_django/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from rest_framework import routers
from rest_framework_jwt.views import obtain_jwt_token

from Apps.personal.views import PersonalAllViewSet, PersonalViewSet, ClientesViewSet, ClientesAllViewSet
from Apps.proveedor.urls import *
from remansoApp.views import *

router = routers.DefaultRouter()
rest_base_url = "api/"

router.register(rest_base_url + "usuarios", UsuarioViewSet)
router.register(rest_base_url + "perfiles", PerfilesViewSet)
router.register(rest_base_url + "proveedores", ProveedoresViewSet)
router.register(rest_base_url + "proveedor", ProveedorViewSet)
router.register(rest_base_url + "personalAll", PersonalAllViewSet)
router.register(rest_base_url + "productos", ProductoViewSet)
router.register(rest_base_url + "productos_proveedor", Categoria_Producto_Serializer)

router.register(rest_base_url + "personal", PersonalViewSet)
router.register(rest_base_url + "clientes", ClientesViewSet)
router.register(rest_base_url + "clientesAll", ClientesAllViewSet)
router.register(rest_base_url + "platos", PlatosViewSet)
router.register(rest_base_url + "ventas", VentasViewSet)
router.register(rest_base_url + "pedidos", PedidosViewSet)




urlpatterns = [
    url(r'^$',login_required(HomeTemplateView.as_view()), name='home'),
    url(r'^login/$', auth_views.login, {'template_name': 'home/login.html'}, name="login"),
    url(r'^logout/$', auth_views.logout, {'next_page': 'home'}, name='logout'),

    url(r'^', include(router.urls)),
    url(r'^proveedor/', include('Apps.proveedor.urls')),
    url(r'^menu/', include('Apps.menu.urls')),
    url(r'^pedidos/', include('Apps.pedido.urls')),
    url(r'^personal/', include('Apps.personal.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^api-token-auth/', obtain_jwt_token)

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/productos/actualizar_stock.html
{#{% extends 'base.html' %}#}
{#{% load staticfiles %}#}
{#{% load static %}#}


{% load  filters %}
<!-- Modal -->
<div class="modal-dialog modal-lg">
    <!-- Modal content-->
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title">{{ titulo_modal }}</h4>
            <button type="button" class="close" data-dismiss="modal">&times;
            </button>

        </div>
        <div class="modal-body">
            <form class="form-horizontal" method="post" role="form" enctype="multipart/form-data" action="{% url 'proveedor:actualizar_stock' producto %}"> {% csrf_token %}


                    <div class="form-group">

                        <label class="col-sm-4 control-label" for="cantidad">Cantidad</label>
                        <div class="col-sm-8">
                            <input id="cantidad" name="cantidad" type="number" value="{{ cantidad_anterior }}">
                        </div>
                    </div>


                <div class="modal-footer">
                    <div class="col-md-6">
                        <div class=" btn-group" role="group">
                            <button type="submit" class="btn btn-primary" name="submit" value="Guardar">Guardar</button>
                            <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>

    </div>
</div>

templates/productos/producto_add.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load static %}
{% block title %} {{ titulo }} {% endblock title %}
{% load  filters %}
{% block head %} {{ titulo | upper}} {% endblock %}
{% block content %}
<!-- Content -->



<!-- Modal -->
{#MODAL CATEGORIA#}
<div id="popup" class="modal fade" role="dialog"></div>
<!--------------------------------------------------------------->

<div class="modal-dialog modal-lg">
    <!-- Modal content-->
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title">{{ titulo_modal }}</h4>
             <button onclick="return abrir_modal('{% url 'proveedor:categoria_create' %}')" class="btn btn-success"><i class="fa fa-plus-circle "> </i> Categoría
                        </button>
        </div>
        <div class="modal-body">
            <form class="form-horizontal" method="post" role="form" enctype="multipart/form-data" action="{% url 'proveedor:producto_add' %}"> {% csrf_token %}

                {% for field in form_producto %}
                    <div class="form-group">
                        {{ field.errors }}
                        <label class="col-sm-4 control-label" for="{{ field.name }}">{{ field.label }}</label>
                        <div class="col-sm-8">
                            {{ field|addclass:'form-control' }}
                        </div>
                    </div>
                {% endfor %}

                <div class="modal-footer">
                    <div class="col-md-6">
                        <div class=" btn-group" role="group">
                            <button type="submit" class="btn btn-primary" name="submit" value="Guardar">Guardar</button>
{#                            <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>#}
                            <a class="btn btn-danger" href="javascript:history.go(-1)">Cancelar</a>
                        </div>
                    </div>
                </div>
            </form>
        </div>

    </div>
</div>
{% endblock %}

{% block javascripts %}
    {{ block.super }}
    <script>
        function abrir_modal(url) {
            $('#popup').load(url, function () {
                $(this).modal('show');
            });
            return false;
        }

        function cerrar_modal() {
            $('#popup').modal('hide');
            return false;
        }
    </script>

{% endblock %}

templates/productos/producto_categoria.html
{% load  filters %}
<!-- Modal -->
<div class="modal-dialog modal-lg">
    <!-- Modal content-->
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title">{{ titulo_modal }}</h4>
            <button type="button" class="close" data-dismiss="modal">&times;</button>

        </div>
        <div class="modal-body">
            <form class="form-horizontal" method="post" role="form" enctype="multipart/form-data" action="{% url 'proveedor:categoria_create' %}"> {% csrf_token %}

                {% for field in form_categoria %}
                    <div class="form-group">
                        {{ field.errors }}
                        <label class="col-sm-4 control-label" for="{{ field.name }}">{{ field.label }}</label>
                        <div class="col-sm-8">
                            {{ field|addclass:'form-control' }}
                        </div>
                    </div>
                {% endfor %}

                <div class="modal-footer">
                    <div class="col-md-6">
                        <div class=" btn-group" role="group">
                            <button type="submit" class="btn btn-primary" name="submit" value="Guardar">Guardar</button>
                            <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>

    </div>
</div>

templates/productos/producto_delete.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load static %}


{% load  filters %}
{% block title %} {{ titulo }} {% endblock title %}
{% block content %}
    <!-- Content -->

    <div class="modal-dialog modal-lg">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                {#            <button type="button" class="close" data-dismiss="modal">&times;</button>#}
                <h4 class="modal-title">{{ titulo_modal }}</h4>
            </div>
            <div class="modal-body">
                 <h3>¿Seguro quiere eliminar éste registro?</h3><br>
                <form method="POST" action="">{% csrf_token %}

{#                    <input class="bg-danger" type="submit" value="Eliminar"/>#}
                    <button type="submit" class="btn btn-danger" name="submit" value="Guardar">Eliminar</button>
                            <button onClick="javascript:history.go(-1)" type="button" class="btn btn-primary" data-dismiss="modal">Cancelar</button>
                </form>

            </div>

        </div>
    </div>
{% endblock %}

templates/productos/producto_list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load static %}


{% block title %} {{ titulo }} {% endblock title %}
{% block content %}

    <!--------------------------MODALES ----------------------------->
<div id="popup" class="modal fade" role="dialog"></div>
<!--------------------------------------------------------------->
    <section class="tables">
        <div class="container-fluid">
            {#              <div class="row">#}

            <div class="col-lg-12">
                <div class="card">

                    <div class="card-header d-flex align-items-center">

{#                         <a href="#" class="btn btn-primary" title="Agregar"> <i class="fa fa-plus-circle"></i> Proveedor</a>#}
                        <a href="{% url 'proveedor:producto_add' %}" class="btn btn-success"><i class="fa fa-plus-circle "> </i> Producto</a>

                    </div>
                    <div class="card-body">
                        <table class="table table-striped">

                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Nombre</th>
                                <th>Categoría</th>
                                <th>Precio</th>
                                <th>Cantidad</th>
                                <th>En Stock</th>
                                 <th>Unidad de medida</th>
                                <th>Fecha Caducidad</th>
                                <th>Acciones</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for producto in object_list %}
                                <tr>
                                    <th scope="row">{{ forloop.counter }}</th>
                                    <td>{{ producto.nombre }}</td>
                                    <td>{{ producto.categoria}}</td>
                                    <td>{{ producto.precio |floatformat:2 }}</td>
                                    <td>{{ producto.cantidad}}</td>
                                    {% if producto.existencia_actual > producto.alerta %}
                                        <td> <button title="Actualizar Stock" onclick="return abrir_modal('{% url 'proveedor:actualizar_stock' producto.pk %}')" class="btn bg-green">
                                        {{ producto.existencia_actual}}</button></td>
                                     {% else %}
                                          <td> <button title="Actualizar Stock" onclick="return abrir_modal('{% url 'proveedor:actualizar_stock' producto.pk %}')" class="btn bg-red">
                                        {{ producto.existencia_actual}}</button></td>
                                    {% endif %}
                                    <td>{{ producto.unidad_medida }}</td>
                                    <td>{{ producto.fecha_caducidad}}</td>
                                    <td><a href="{% url 'proveedor:producto_update' producto.pk %}" title="Editar"> <i class="fa fa-edit"></i></a>
                                        <a href="{% url 'proveedor:producto_delete' producto.pk %}" title="Borrar"> <i class="fa fa-trash"></i></a>
                                    </td>
                                </tr>
                            {% empty %}
                                <h3>No hay datos que mostrar!</h3>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}


{% block javascripts %}
    {{ block.super }}
    <script>
        function abrir_modal(url) {
            $('#popup').load(url, function () {
                $(this).modal('show');
            });
            return false;
        }

        function cerrar_modal() {
            $('#popup').modal('hide');
            return false;
        }
    </script>

{% endblock %}

templates/productos/producto_update.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load static %}


{% load  filters %}
{% block title %} {{ titulo }} {% endblock title %}
{% block content %}
<!-- Content -->

<div class="modal-dialog modal-lg">
    <!-- Modal content-->
    <div class="modal-content">
        <div class="modal-header">
{#            <button type="button" class="close" data-dismiss="modal">&times;</button>#}
            <h4 class="modal-title">{{ titulo_modal }}</h4>
        </div>
        <div class="modal-body">
            <form class="form-horizontal" method="post" role="form" enctype="multipart/form-data" action=""> {% csrf_token %}

                {% for field in form %}
                    <div class="form-group">
                        {{ field.errors }}
                        <label class="col-sm-4 control-label" for="{{ field.name }}">{{ field.label }}</label>
                        <div class="col-sm-8">
                            {{ field|addclass:'form-control' }}
                        </div>
                    </div>
                {% endfor %}

                <div class="modal-footer">
                    <div class="col-md-6">
                        <div class=" btn-group" role="group">
                            <button type="submit" class="btn btn-primary" name="submit" value="Guardar">Guardar</button>
                            <button onClick="javascript:history.go(-1)" type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>

    </div>
</div>
{% endblock %}