Apps/menu/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required

from Apps.menu.views import *

app_name = 'menu'


urlpatterns = [
    url(r'^menu_list/$', login_required(MenuListView.as_view()), name='menu_list'),
    url(r'^menu_add/$', menuCreate, name='menu_add'),
    url(r'^menu_update/(?P<pk>\d+)$', MenuUpdate.as_view(), name='menu_update'),
    url(r'^menu_delete/(?P<pk>\d+)$', MenuDelete.as_view(), name='menu_delete'),
    # Categorias Productos
    url(r'^categoria_create/$', categoriaCreate, name='categoria_create'),
    # Actualizar Stock
    url(r'^actualizar_stock/(?P<pk>\d+)$', actualizarStock, name='actualizar_stock'),

]

Apps/pedido/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required

from Apps.pedido.views import *

app_name = 'pedido'
urlpatterns = [
    # url(r'^api_menus/$', api_menus, name='api_menus'),

    url(r'^pedidos_list/$', login_required(PedidosListView.as_view()), name='pedidos_list'),
    url(r'^pedido_add/$', pedidoCreate, name='pedido_add'),
    url(r'^crear_pedido/(?P<mesa>\d+)$', CrearPedido, name='crear_pedido'),
    url(r'^pedido_delete/(?P<pk>\d+)$', eliminarPedido, name='pedido_delete'),


    url(r'^mesas_list/$', login_required(MesasListView.as_view()), name='mesas_list'),
    url(r'^mesa_add/$', mesaCreate, name='mesa_add'),
    url(r'^mesa_delete/(?P<pk>\d+)$', MesaDelete.as_view(), name='mesa_delete'),
    url(r'^mesa_open/(?P<mesa_pk>\d+)$', mesaOpen, name='mesa_open'),


    url(r'^add_menu_pedido/(?P<mesa>\d+)/(?P<menu>\d+)/(?P<pedido>\d+)$', agragarMenuPedido, name='add_menu_pedido'),
    url(r'^delete_menu_pedido/(?P<mesa>\d+)/(?P<menu>\d+)/(?P<pedido>\d+)$', eliminarMenuPedido, name='delete_menu_pedido'),
    url(r'^restar_menu_pedido/(?P<mesa>\d+)/(?P<menu>\d+)/(?P<pedido>\d+)$', restarMenuPedido, name='restar_menu_pedido'),





    # url(r'^menu_update/(?P<pk>\d+)$', MenuUpdate.as_view(), name='menu_update'),
    # url(r'^menu_delete/(?P<pk>\d+)$', MenuDelete.as_view(), name='menu_delete'),
    # # Categorias Productos
    # url(r'^categoria_create/$', categoriaCreate, name='categoria_create'),
    # # Actualizar Stock
    # url(r'^actualizar_stock/(?P<pk>\d+)$', actualizarStock, name='actualizar_stock'),

]

Apps/personal/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required

from Apps.personal.views import *

app_name = 'personal'


urlpatterns = [
    url(r'^personal_list/$', login_required(PersonalListView.as_view()), name='personal_list'),
    url(r'^personal_add/$', personal_create, name='personal_add'),
    url(r'^personal_update/(?P<pk>\d+)$', update, name='personal_update'),
    url(r'^personal_delete/(?P<pk>\d+)$', Delete.as_view(), name='personal_delete'),

    url(r'^cliente_list/$', login_required(ClienteListView.as_view()), name='cliente_list'),
    url(r'^cliente_add/$', createCliente, name='cliente_add'),
    url(r'^cliente_update/(?P<pk>\d+)$', updateCliente, name='cliente_update'),
    url(r'^cliente_delete/(?P<pk>\d+)$', DeleteCliente.as_view(), name='cliente_delete'),


]

Apps/proveedor/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required

from Apps.proveedor.views import *

app_name = 'proveedor'
urlpatterns = [
    # proveedores
    url(r'^proveedor_list/$', login_required(ProveedoresListView.as_view()), name='proveedor_list'),
    url(r'^proveedor_detail/(?P<pk>\d+)$', ProveedoresDetailView.as_view(), name='proveedor_detail'),
    url(r'^proveedor_add/$', proveedor_create, name='proveedor_add'),
    url(r'^proveedor_update/(?P<pk>\d+)$', Update.as_view(), name='proveedor_update'),
    url(r'^proveedor_delete/(?P<pk>\d+)$', Delete.as_view(), name='proveedor_delete'),

    # productos
    url(r'^producto_list/$', login_required(ProductosListView.as_view()), name='producto_list'),
    url(r'^producto_detail/(?P<pk>\d+)$', ProductosDetailView.as_view(), name='producto_detail'),
    url(r'^producto_add/$', productoCreate, name='producto_add'),
    url(r'^producto_update/(?P<pk>\d+)$', ProductoUpdate.as_view(), name='producto_update'),
    url(r'^producto_delete/(?P<pk>\d+)$', ProductoDelete.as_view(), name='producto_delete'),

    # Categorias Productos
    url(r'^categoria_create/$', categoriaCreate, name='categoria_create'),

    # Actualizar Stock
    url(r'^actualizar_stock/(?P<pk>\d+)$', actualizarStock, name='actualizar_stock')

]

remanso_django/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from rest_framework import routers
from rest_framework_jwt.views import obtain_jwt_token

from Apps.personal.views import PersonalAllViewSet, PersonalViewSet, ClientesViewSet, ClientesAllViewSet
from Apps.proveedor.urls import *
from remansoApp.views import *

router = routers.DefaultRouter()
rest_base_url = "api/"

router.register(rest_base_url + "usuarios", UsuarioViewSet)
router.register(rest_base_url + "perfiles", PerfilesViewSet)
router.register(rest_base_url + "proveedores", ProveedoresViewSet)
router.register(rest_base_url + "proveedor", ProveedorViewSet)
router.register(rest_base_url + "personalAll", PersonalAllViewSet)
router.register(rest_base_url + "productos", ProductoViewSet)
router.register(rest_base_url + "productos_proveedor", Categoria_Producto_Serializer)

router.register(rest_base_url + "personal", PersonalViewSet)
router.register(rest_base_url + "clientes", ClientesViewSet)
router.register(rest_base_url + "clientesAll", ClientesAllViewSet)
router.register(rest_base_url + "platos", PlatosViewSet)
router.register(rest_base_url + "ventas", VentasViewSet)
router.register(rest_base_url + "pedidos", PedidosViewSet)




urlpatterns = [
    url(r'^$',login_required(HomeTemplateView.as_view()), name='home'),
    url(r'^login/$', auth_views.login, {'template_name': 'home/login.html'}, name="login"),
    url(r'^logout/$', auth_views.logout, {'next_page': 'home'}, name='logout'),

    url(r'^', include(router.urls)),
    url(r'^proveedor/', include('Apps.proveedor.urls')),
    url(r'^menu/', include('Apps.menu.urls')),
    url(r'^pedidos/', include('Apps.pedido.urls')),
    url(r'^personal/', include('Apps.personal.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^api-token-auth/', obtain_jwt_token)

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load staticfiles %}
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}El Remanso{% endblock %}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap4.min.css' %}">
    <!-- Fontastic Custom icon font-->
    <link rel="stylesheet" href="{% static 'css/fontastic.css' %}">
    <!-- Font Awesome CSS-->
    <link rel="stylesheet" href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}">
    {#        <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">#}
    <!-- Google fonts - Poppins -->
    <link rel="stylesheet" href="{% static 'css/google_fonts.css' %}">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="{% static 'css/style.default.css' %}" id="theme-stylesheet">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <!-- Favicon-->
    <link rel="shortcut icon" href="favicon.png">
    <!-- Tweaks for older IEs--><!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
</head>
<body>
<div class="page home-page">
    <!-- Main Navbar-->
    <header class="header">
        <nav class="navbar">
            <!-- Search Box-->
            <div class="search-box">
                <button class="dismiss"><i class="icon-close"></i></button>
                <form id="searchForm" action="#" role="search">
                    <input type="search" placeholder="What are you looking for..." class="form-control">
                </form>
            </div>
            <div class="container-fluid">
                <div class="navbar-holder d-flex align-items-center justify-content-between">
                    <!-- Navbar Header-->
                    <div class="navbar-header">
                        <!-- Navbar Brand --><a href="index.html" class="navbar-brand">
                        <div class="brand-text brand-big"><span>Hosteria</span> <strong> El Remanso</strong></div>
                        <div class="brand-text brand-small"><strong>BD</strong></div>
                    </a>
                        <!-- Toggle Button--><a id="toggle-btn" href="#" class="menu-btn active"><span></span><span></span><span></span></a>
                    </div>
                    <!-- Navbar Menu -->
                    <ul class="nav-menu list-unstyled d-flex flex-md-row align-items-md-center">
                        <!-- Search-->
                        <li class="nav-item d-flex align-items-center"><a id="search" href="#"><i class="icon-search"></i></a></li>
                        <!-- Notifications-->
                        <li class="nav-item dropdown"><a id="notifications" rel="nofollow" data-target="#" href="#" data-toggle="dropdown"
                                                         aria-haspopup="true" aria-expanded="false" class="nav-link"><i class="fa fa-bell-o"></i><span
                                class="badge bg-red">12</span></a>
                            <ul aria-labelledby="notifications" class="dropdown-menu">
                                <li><a rel="nofollow" href="#" class="dropdown-item">
                                    <div class="notification">
                                        <div class="notification-content"><i class="fa fa-envelope bg-green"></i>You have 6 new messages</div>
                                        <div class="notification-time">
                                            <small>4 minutes ago</small>
                                        </div>
                                    </div>
                                </a></li>
                                <li><a rel="nofollow" href="#" class="dropdown-item">
                                    <div class="notification">
                                        <div class="notification-content"><i class="fa fa-twitter bg-blue"></i>You have 2 followers</div>
                                        <div class="notification-time">
                                            <small>4 minutes ago</small>
                                        </div>
                                    </div>
                                </a></li>
                                <li><a rel="nofollow" href="#" class="dropdown-item">
                                    <div class="notification">
                                        <div class="notification-content"><i class="fa fa-upload bg-orange"></i>Server Rebooted</div>
                                        <div class="notification-time">
                                            <small>4 minutes ago</small>
                                        </div>
                                    </div>
                                </a></li>
                                <li><a rel="nofollow" href="#" class="dropdown-item">
                                    <div class="notification">
                                        <div class="notification-content"><i class="fa fa-twitter bg-blue"></i>You have 2 followers</div>
                                        <div class="notification-time">
                                            <small>10 minutes ago</small>
                                        </div>
                                    </div>
                                </a></li>
                                <li><a rel="nofollow" href="#" class="dropdown-item all-notifications text-center"> <strong>view all
                                    notifications </strong></a></li>
                            </ul>
                        </li>


                        <!-- Logout    -->
                        <li class="nav-item"><a href="{% url 'logout' %}" class="nav-link logout">Salir<i class="fa fa-sign-out"></i></a></li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="page-content d-flex align-items-stretch">
        <!-- Side Navbar -->
        <nav class="side-navbar">
            <!-- Sidebar Header-->
            <div class="sidebar-header d-flex align-items-center">
                <div class="avatar"><img src="{% static 'img/avatar-1.jpg' %}" alt="..." class="img-fluid rounded-circle"></div>
                <div class="title">
                    <h1 class="h4">Mark Stephen</h1>
                    <p>Web Designer</p>
                </div>
            </div>
            <!-- Sidebar Navidation Menus-->
            {#            <span class="heading">Main</span>#}
            <ul class="list-unstyled">
                <li class="{{ inicio_activo }}"><a href="{% url 'home' %}"><i class="fa fa-home"></i>INICIO</a></li>
                <li class="{{ pedido_activo }}"><a href="{% url 'pedido:pedidos_list' %}"> <i class="icon-padnote"></i>PEDIDOS </a></li>
                 <li class="{{ menu_activo }}"><a href="{% url 'menu:menu_list' %}"> <i class="fa fa-cutlery"></i>MENÚ</a></li>
                <li class="{{ personal_activo }}"><a href="{% url 'personal:personal_list' %}"> <i class="fa fa-address-card"></i>PERSONAL </a></li>
                {#                <li class="{{ proveedor_activo }}"><a href="#dashvariants" aria-expanded="false" data-toggle="collapse"> <i class="fa fa-shopping-basket"></i>COMPRAS</a>#}
                {#                    <ul id="dashvariants" class="collapse list-unstyled">#}
                {#                        <li class="{{ proveedor_activo }}"><a  href="{% url 'proveedor:proveedor_list' %}"> <i class="fa fa-truck"></i>PROVEEDORES </a></li>#}
                {#                        <li class="{{ producto_activo }}"><a href="{% url 'proveedor:producto_list' %}"> <i class="fa fa-cart-plus"></i>PRODUCTOS </a>#}
                {##}
                {##}
                {#                    </ul>#}
                {#                </li>#}
                <li class="{{ cliente_activo }}"><a href="{% url 'personal:cliente_list' %}"> <i class="fa fa-users"></i>CLIENTES</a></li>
                <li class="{{ proveedor_activo }}"><a href="{% url 'proveedor:proveedor_list' %}"> <i class="fa fa-truck"></i>PROVEEDORES </a></li>
                <li class="{{ producto_activo }}"><a href="{% url 'proveedor:producto_list' %}"> <i class="fa fa-shopping-basket"></i>PRODUCTOS </a>
                <li class="{{ mesa_activo }}"><a href="{% url 'pedido:mesas_list' %}"> <i class="fa fa-building"></i>MESAS </a>
                <li class="{{ ayuda_activo }}"><a href="#"> <i class="fa fa-question-circle"></i>AYUDA</a>
{#                <li class="{{ ayuda_activo }}"><a href="#"> <img src="{% static 'img/terrace.svg' %}" style="height: 15px; width: 15px" alt="Kiwi standing on oval"> AYUDA</a>#}
            </ul>
        </nav>

        <div class="content-inner">
            <!-- Page Header-->
            <header class="page-header">
                <div class="container-fluid">
                    <h2 class="no-margin-bottom">{% block head %} {{ titulo| upper }}    {% endblock %} </h2>

                </div>
            </header>
            {% block content %}

            {% endblock content %}
            <!-- Page Footer-->
            <footer class="main-footer">


                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-6">
                            <p>El Remanso &copy; 2017-2019</p>
                        </div>
                        <div class="col-sm-6 text-right">
                            <p>Design by <a href="https://bootstrapious.com/admin-templates" class="external">Bootstrapious</a></p>
                            <!-- Please do not remove the backlink to us unless you support further theme's development at https://bootstrapious.com/donate. It is part of the license conditions. Thank you for understanding :)-->
                        </div>
                    </div>
                </div>

            </footer>
        </div>

    </div>


    {% block javascripts %}
        <!-- Javascript files-->
        <script src="{% static 'js/jquery.min.js' %}"></script>
{#        <script src="{% static 'vendor/jquery/jquery.slim.js' %}"></script>#}
        <script src="{% static 'vendor/bootstrap/js/popper.min.js' %}"></script>
        <script src="{% static 'vendor/bootstrap/js/bootstrap4.min.js' %}"></script>
        <script src="/static/vendor/jquery.cookie/jquery.cookie.js"></script>
        <script src="/static/vendor/jquery-validation/jquery.validate.min.js"></script>
        <script src="{% static 'js/Chart.min.js' %}"></script>
        <script src="/static/js/charts-home.js"></script>
        <script src="/static/js/front.js"></script>
    {% endblock %}
</div>
</body>
</html>