Apps/menu/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required

from Apps.menu.views import *

app_name = 'menu'


urlpatterns = [
    url(r'^menu_list/$', login_required(MenuListView.as_view()), name='menu_list'),
    url(r'^menu_add/$', menuCreate, name='menu_add'),
    url(r'^menu_update/(?P<pk>\d+)$', MenuUpdate.as_view(), name='menu_update'),
    url(r'^menu_delete/(?P<pk>\d+)$', MenuDelete.as_view(), name='menu_delete'),
    # Categorias Productos
    url(r'^categoria_create/$', categoriaCreate, name='categoria_create'),
    # Actualizar Stock
    url(r'^actualizar_stock/(?P<pk>\d+)$', actualizarStock, name='actualizar_stock'),

]

remanso_django/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from rest_framework import routers
from rest_framework_jwt.views import obtain_jwt_token

from Apps.personal.views import PersonalAllViewSet, PersonalViewSet, ClientesViewSet, ClientesAllViewSet
from Apps.proveedor.urls import *
from remansoApp.views import *

router = routers.DefaultRouter()
rest_base_url = "api/"

router.register(rest_base_url + "usuarios", UsuarioViewSet)
router.register(rest_base_url + "perfiles", PerfilesViewSet)
router.register(rest_base_url + "proveedores", ProveedoresViewSet)
router.register(rest_base_url + "proveedor", ProveedorViewSet)
router.register(rest_base_url + "personalAll", PersonalAllViewSet)
router.register(rest_base_url + "productos", ProductoViewSet)
router.register(rest_base_url + "productos_proveedor", Categoria_Producto_Serializer)

router.register(rest_base_url + "personal", PersonalViewSet)
router.register(rest_base_url + "clientes", ClientesViewSet)
router.register(rest_base_url + "clientesAll", ClientesAllViewSet)
router.register(rest_base_url + "platos", PlatosViewSet)
router.register(rest_base_url + "ventas", VentasViewSet)
router.register(rest_base_url + "pedidos", PedidosViewSet)




urlpatterns = [
    url(r'^$',login_required(HomeTemplateView.as_view()), name='home'),
    url(r'^login/$', auth_views.login, {'template_name': 'home/login.html'}, name="login"),
    url(r'^logout/$', auth_views.logout, {'next_page': 'home'}, name='logout'),

    url(r'^', include(router.urls)),
    url(r'^proveedor/', include('Apps.proveedor.urls')),
    url(r'^menu/', include('Apps.menu.urls')),
    url(r'^pedidos/', include('Apps.pedido.urls')),
    url(r'^personal/', include('Apps.personal.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^api-token-auth/', obtain_jwt_token)

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Apps/menu/models.py
from django.db import models
from Apps.proveedor.models import Producto


# Create your models here.

# ---------------------------------------------------------------------------

class Menu_Categoria(models.Model):
    categoria = models.CharField(max_length=50)

    def __str__(self):
        return '%s' % (self.categoria)


# ---------------------------------------------


TIPO_MENU = (('carta', 'A la Carta'), ('desayuno', 'Desayuno'), ('almuerzo', 'Almuerzo'), ('merienda', 'Merienda'),
             ('bebida', 'Bebida'), ('otro', 'Otro'))


class Menu(models.Model):
    tipo = models.CharField(null=True, blank=True, max_length=10, choices=TIPO_MENU)
    nombre = models.CharField(verbose_name='Nombre',max_length=200)
    imagen = models.ImageField(null=False, blank=True, upload_to='menuFoto', verbose_name='Imágen')
    descripcion = models.CharField(verbose_name='Descripcción',max_length=200, null=True, blank=True)
    precio = models.FloatField(verbose_name='Precio',null=False, blank=False)
    categoria = models.ForeignKey(Menu_Categoria, verbose_name='Categoría',on_delete=models.CASCADE, null=True, blank=True)
    cantidad_diaria = models.IntegerField(verbose_name='Cantidad',null=True, blank=True)
    existencia_actual = models.IntegerField(verbose_name='En Stock',null=True, blank=True)
    alerta = models.IntegerField(verbose_name='Alerta, cuando catidad es menor a', null=True, blank=True)
    activo = models.BooleanField(default=True)


    def __str__(self):
        return "%s" % (self.nombre)

    class Meta:
        verbose_name_plural = 'Menu'


# ---------------------------------------------

class Producto_Menu(models.Model):
    menu = models.ForeignKey(Menu, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad_prod_utilizado = models.IntegerField()

Apps/menu/forms.py
from django.forms import ModelForm
from django import forms

from Apps.menu.models import Menu, Menu_Categoria
from Apps.personal.models import Perfil
from Apps.proveedor.models import *


class MenuForm(ModelForm):
    class Meta:
        model = Menu
        fields = '__all__'
        exclude = ['id','tipo', 'existencia_actual', 'activo']

class MenuUpdateForm(ModelForm):
    class Meta:
        model = Menu
        fields = '__all__'
        exclude = ['id','tipo', 'existencia_actual', 'cantidad_diaria']

class CategoriaMenuForm(ModelForm):
    class Meta:
        model = Menu_Categoria
        fields = '__all__'
        exclude = ['id']

Apps/menu/views.py
from django.contrib.admin.views.decorators import staff_member_required
from django.shortcuts import render, redirect

# -------- VIEWS PRODUCTOS-----------
from django.urls import reverse
from django.views.generic import DetailView, ListView, UpdateView, DeleteView

from Apps.menu.forms import MenuForm, CategoriaMenuForm, MenuUpdateForm
from Apps.menu.models import Menu
from Apps.proveedor.forms import CategoriaForm


class MenuDetailView(DetailView):
    model = Menu
    template_name = 'menu/menu_list.html'


# --------------------------------------
class MenuListView(ListView):
    model = Menu
    template_name = 'menu/menu_list.html'

    def get_queryset(self, *args, **kwargs):
        qs = super(MenuListView, self).get_queryset(*args, **kwargs)
        return qs

    def get_context_data(self, *args, **kwargs):
        context = super(MenuListView, self).get_context_data(*args, **kwargs)
        context['titulo'] = "Menú"
        context['menu_activo'] = 'active'
        return context


# --------------------------------------
def menuCreate(request):
    form_menu = MenuForm(request.POST or None, request.FILES or None)
    contex = {'form_producto': form_menu, 'titulo': 'Menú', 'titulo_modal': 'Nuevo Menú'}
    if request.method == 'POST':
        if form_menu.is_valid():
            menu = form_menu.save(commit=False)
            menu.existencia_actual = request.POST.get('cantidad_diaria')
            menu.save()
            return redirect('menu:menu_list')
    return render(request, 'menu/menu_add.html', contex)


# --------------------------------------
class MenuUpdate(UpdateView):
    model = Menu
    form_class = MenuUpdateForm
    template_name = "menu/menu_update.html"

    def get_context_data(self, *args, **kwargs):
        context = super(MenuUpdate, self).get_context_data(*args, **kwargs)
        context['titulo'] = "Menú"
        context['titulo_modal'] = "Actualizar Menú"
        return context

    def get_success_url(self):
        return reverse('menu:menu_list')


# --------------------------------------
class MenuDelete(DeleteView):
    model = Menu
    template_name = "menu/menu_delete.html"

    def get_success_url(self):
        return reverse('menu:menu_list')


# --------------------------------------
def categoriaCreate(request):
    form_categoria = CategoriaMenuForm(request.POST or None)
    contex = {'form_categoria': form_categoria, 'titulo': 'Menu', 'titulo_modal': 'Categoría Menú'}
    if request.method == 'POST':
        if form_categoria.is_valid():
            form_categoria.save()
            return redirect('menu:menu_add')
    return render(request, 'menu/menu_categoria.html', contex)


# --------------------------------------

def actualizarStock(request, pk):
    try:
        menu = Menu.objects.get(pk=pk)
        cantidad_anterior = menu.existencia_actual
        if request.method == 'POST':
            cantidad_actual = int(request.POST.get('cantidad'))
            if cantidad_actual != cantidad_anterior:
                cantidad = cantidad_actual
                Menu.objects.filter(pk=pk).update(existencia_actual=cantidad, cantidad_diaria=cantidad)
            return redirect('menu:menu_list')
    except:
        pass

    return render(request, 'menu/actualizar_stock.html', {'menu': pk, 'titulo_modal':'Actualizar Stock', 'cantidad_anterior': cantidad_anterior })

templates/menu/actualizar_stock.html
{#{% extends 'base.html' %}#}
{#{% load staticfiles %}#}
{#{% load static %}#}


{% load  filters %}
<!-- Modal -->
<div class="modal-dialog modal-lg">
    <!-- Modal content-->
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title">{{ titulo_modal }}</h4>
            <button type="button" class="close" data-dismiss="modal">&times;
            </button>

        </div>
        <div class="modal-body">
            <form class="form-horizontal" method="post" role="form" enctype="multipart/form-data" action="{% url 'menu:actualizar_stock' menu %}"> {% csrf_token %}


                    <div class="form-group">

                        <label class="col-sm-4 control-label" for="cantidad">Cantidad</label>
                        <div class="col-sm-8">
                            <input id="cantidad" name="cantidad" type="number" value="{{ cantidad_anterior }}">
                        </div>
                    </div>


                <div class="modal-footer">
                    <div class="col-md-6">
                        <div class=" btn-group" role="group">
                            <button type="submit" class="btn btn-primary" name="submit" value="Guardar">Guardar</button>
                            <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>

    </div>
</div>

templates/menu/menu_add.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load static %}
{% block title %} {{ titulo }} {% endblock title %}
{% load  filters %}
{% block head %} {{ titulo | upper}} {% endblock %}
{% block content %}
<!-- Content -->



<!-- Modal -->
{#MODAL CATEGORIA#}
<div id="popup" class="modal fade" role="dialog"></div>
<!--------------------------------------------------------------->

<div class="modal-dialog modal-lg">
    <!-- Modal content-->
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title">{{ titulo_modal }}</h4>
             <button onclick="return abrir_modal('{% url 'menu:categoria_create' %}')" class="btn btn-success"><i class="fa fa-plus-circle "> </i> Categoría
                        </button>
        </div>
        <div class="modal-body">
            <form class="form-horizontal" method="post" role="form" enctype="multipart/form-data" action="{% url 'menu:menu_add' %}"> {% csrf_token %}

                {% for field in form_producto %}
                    <div class="form-group">
                        {{ field.errors }}
                        <label class="col-sm-4 control-label" for="{{ field.name }}">{{ field.label }}</label>
                        <div class="col-sm-8">
                            {{ field|addclass:'form-control' }}
                        </div>
                    </div>
                {% endfor %}

                <div class="modal-footer">
                    <div class="col-md-6">
                        <div class=" btn-group" role="group">
                            <button type="submit" class="btn btn-primary" name="submit" value="Guardar">Guardar</button>
{#                            <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>#}
                            <a class="btn btn-danger" href="javascript:history.go(-1)">Cancelar</a>
                        </div>
                    </div>
                </div>
            </form>
        </div>

    </div>
</div>
{% endblock %}

{% block javascripts %}
    {{ block.super }}
    <script>
        function abrir_modal(url) {
            $('#popup').load(url, function () {
                $(this).modal('show');
            });
            return false;
        }

        function cerrar_modal() {
            $('#popup').modal('hide');
            return false;
        }
    </script>

{% endblock %}

templates/menu/menu_categoria.html
{% load  filters %}
<!-- Modal -->
<div class="modal-dialog modal-lg">
    <!-- Modal content-->
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title">{{ titulo_modal }}</h4>
            <button type="button" class="close" data-dismiss="modal">&times;
            </button>

        </div>
        <div class="modal-body">
            <form class="form-horizontal" method="post" role="form" enctype="multipart/form-data" action="{% url 'menu:categoria_create' %}"> {% csrf_token %}

                {% for field in form_categoria %}
                    <div class="form-group">
                        {{ field.errors }}
                        <label class="col-sm-4 control-label" for="{{ field.name }}">{{ field.label }}</label>
                        <div class="col-sm-8">
                            {{ field|addclass:'form-control' }}
                        </div>
                    </div>
                {% endfor %}

                <div class="modal-footer">
                    <div class="col-md-6">
                        <div class=" btn-group" role="group">
                            <button type="submit" class="btn btn-primary" name="submit" value="Guardar">Guardar</button>
                            <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>

    </div>
</div>

templates/menu/menu_delete.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load static %}


{% load  filters %}
{% block title %} {{ titulo }} {% endblock title %}
{% block content %}
    <!-- Content -->

    <div class="modal-dialog modal-lg">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                {#            <button type="button" class="close" data-dismiss="modal">&times;</button>#}
                <h4 class="modal-title">{{ titulo_modal }}</h4>
            </div>
            <div class="modal-body">
                 <h3>¿Seguro quiere eliminar éste registro?</h3><br>
                <form method="POST" action="">{% csrf_token %}

{#                    <input class="bg-danger" type="submit" value="Eliminar"/>#}
                    <button type="submit" class="btn btn-danger" name="submit" value="Guardar">Eliminar</button>
                            <button onClick="javascript:history.go(-1)" type="button" class="btn btn-primary" data-dismiss="modal">Cancelar</button>
                </form>

            </div>

        </div>
    </div>
{% endblock %}

templates/menu/menu_list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load static %}


{% block title %} {{ titulo }} {% endblock title %}
{% block content %}

    <!--------------------------MODALES ----------------------------->
<div id="popup" class="modal fade" role="dialog"></div>
<!--------------------------------------------------------------->
    <section class="tables">
        <div class="container-fluid">
            {#              <div class="row">#}
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header d-flex align-items-center">
{#                         <a href="#" class="btn btn-primary" title="Agregar"> <i class="fa fa-plus-circle"></i> Proveedor</a>#}
                        <a href="{% url 'menu:menu_add' %}" class="btn btn-success"><i class="fa fa-plus-circle "> </i> Menú</a>

                    </div>
                    <div class="card-body">
                        <table class="table table-striped">
                            <thead>
                            <tr>
                                <th>#</th>
{#                                <th>Imágen</th>#}
                                <th>Nombre</th>
                                <th>Categoría</th>
                                <th>Precio</th>
                                <th>Cantidad_diaria</th>
                                 <th>En Stock</th>
                                <th>descripcion</th>
                                <th>Activo</th>
                                <th>Acciones</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for menu in object_list %}
                                <tr>
                                    <td scope="row">{{ forloop.counter }}</td>
{#                                    <td>{{ menu.imagen }}</td>#}
                                    <td>{{ menu.nombre }}</td>
                                    <td>{{ menu.categoria}}</td>
                                    <td>{{ menu.precio |floatformat:2 }}</td>
                                    <td>{{ menu.cantidad_diaria }}</td>
                                     {% if menu.existencia_actual > menu.alerta %}
                                        <td> <button title="Actualizar Stock" onclick="return abrir_modal('{% url 'menu:actualizar_stock' menu.pk %}')" class="btn bg-green">
                                        {{ menu.existencia_actual}}</button></td>
                                     {% else %}
                                          <td> <button title="Actualizar Stock" onclick="return abrir_modal('{% url 'menu:actualizar_stock' menu.pk %}')" class="btn bg-red">
                                        {{ menu.existencia_actual}}</button></td>
                                    {% endif %}
                                    <td>{{ menu.descripcion}}</td>
                                    <td>{{ menu.activo}}</td>
                                    <td><a href="{% url 'menu:menu_update' menu.pk %}" title="Editar"> <i class="fa fa-edit"></i></a>
                                        <a href="{% url 'menu:menu_delete' menu.pk %}" title="Borrar"> <i class="fa fa-trash"></i></a>
                                    </td>
                                </tr>
                            {% empty %}
                                <h3>No hay datos que mostrar!</h3>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}


{% block javascripts %}
    {{ block.super }}
    <script>
        function abrir_modal(url) {
            $('#popup').load(url, function () {
                $(this).modal('show');
            });
            return false;
        }

        function cerrar_modal() {
            $('#popup').modal('hide');
            return false;
        }
    </script>

{% endblock %}

templates/menu/menu_update.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load static %}


{% load  filters %}
{% block title %} {{ titulo }} {% endblock title %}
{% block content %}
<!-- Content -->

<div class="modal-dialog modal-lg">
    <!-- Modal content-->
    <div class="modal-content">
        <div class="modal-header">
{#            <button type="button" class="close" data-dismiss="modal">&times;</button>#}
            <h4 class="modal-title">{{ titulo_modal }}</h4>
        </div>
        <div class="modal-body">
            <form class="form-horizontal" method="post" role="form" enctype="multipart/form-data" action=""> {% csrf_token %}

                {% for field in form %}
                    <div class="form-group">
                        {{ field.errors }}
                        <label class="col-sm-4 control-label" for="{{ field.name }}">{{ field.label }}</label>
                        <div class="col-sm-8">
                            {{ field|addclass:'form-control' }}
                        </div>
                    </div>
                {% endfor %}

                <div class="modal-footer">
                    <div class="col-md-6">
                        <div class=" btn-group" role="group">
                            <button type="submit" class="btn btn-primary" name="submit" value="Guardar">Guardar</button>
                            <button onClick="javascript:history.go(-1)" type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>

    </div>
</div>
{% endblock %}